name: 'PageSpeed Insights Action'
description: 'This is an action that outputs PageSpeed Insights results.'
author: 'stefafafan'
inputs:
  url:
    required: true
    description: 'The URL to fetch PageSpeed Insights results.'
  api-key:
    required: true
    description: 'API Key for the PageSpeed Insights API.'
  strategy:
    required: false
    description: 'Strategy to fetch PageSpeed Insights results. "mobile" or "desktop".'
    default: 'desktop'
runs:
  using: 'node16'
  main: 'dist/index.js'
