name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: psi
        uses: ./
        with:
          url: 'https://blog.stenyan.jp/'
          key: ${{ secrets.API_KEY }}
          strategy: 'desktop'
      - name: Echo outputs
        run: |
          echo "Score: ${{ steps.psi.outputs.score }}"
          echo "FCP: ${{ steps.psi.outputs.fcp }}"
          echo "FID: ${{ steps.psi.outputs.fid }}"
          echo "CLS: ${{ steps.psi.outputs.cls }}"
          echo "LCP: ${{ steps.psi.outputs.lcp }}"
          echo "SI: ${{ steps.psi.outputs.si }}"
          echo "TTI: ${{ steps.psi.outputs.tti }}"
          echo "TBT: ${{ steps.psi.outputs.tbt }}"
